---
- name: Install Docker on EC2 instances
  hosts: nodes
  become: true
  tasks:
    - name: Copy Docker installation script
      copy:
        src: ./docker-install.sh
        dest: /tmp/docker-install.sh
        mode: '0755'

    - name: Run Docker installation script
      command: /tmp/docker-install.sh
